name: update loc every 6 hours
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: update
        run: |
          python -m pip install requests
          "LOC=$(python update.py)" >> $GITHUB_ENV

      - name: Test
        run: echo $LOC

      - name: Generate the badge SVG image
        uses: emibcn/badge-action@v1
        id: badge
        with:
          label: 'Lines of Code'
          color: 'blue,555,daf'
          path: $LOC