name: update loc every 6 hours
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: update
        env: 
            GITHUB_TOKEN: ${{ secrets.PRIVATE }}
        run: |
         python -m pip install requests
          echo "LOC=$(python update.py)" >> $GITHUB_ENV
          echo $LOC
      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.4.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 17941a30ee9756244bfb9e1526fa6304
          filename: test.json
          label: Lines of Code
          message: ${{ env.LOC }}
          color: black
